dist: trusty

language: php

php:
  - 5.6
  - 7.1

before_script:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
